---
- name: Get k3s installed version
  ansible.builtin.command: k3s --version
  register: k3s_version_output
  changed_when: false
  ignore_errors: true

- name: Set k3s installed version
  when: k3s_version_output.rc == 0
  ansible.builtin.set_fact:
    installed_k3s_version: "{{ k3s_version_output.stdout_lines[0].split(' ')[2] }}"

- name: Install k3s [agent]
  # Assume failure means it doesn't exist
  when: k3s_version_output.rc > 0 and agent_group in group_names 
  block: 
    - name: Download binary [agent]
      become: true
      ansible.builtin.get_url:
        url: https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version | urlencode }}/k3s
        dest: /usr/local/bin/k3s
        mode: '0755' 
    - name: "Create initial service file [agent]"
      become: true
      ansible.builtin.file:
        path: "{{ systemd_dir }}/system/k3s-agent.service"
        state: touch
        mode: 0600

- name: Update only if needed
  when: installed_k3s_version is defined and installed_k3s_version is version('v' + k3s_version, '<')
  block:
    - name: Stop K3s service [server]
      when: "server_group in group_names"
      become: true
      ansible.builtin.systemd:
        state: stopped
        name: k3s

    - name: Stop K3s service [agent]
      when: "agent_group in group_names"
      become: true
      ansible.builtin.systemd:
        state: stopped
        name: k3s-agent

    - name: Download new binary
      become: true
      ansible.builtin.get_url:
        url: https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version | urlencode }}/k3s
        dest: /usr/local/bin/k3s
        mode: '0755'
        force: true # Otherwise binary isn't updated. 

    - name: Restart K3s service [server]
      when: "server_group in group_names"
      become: true
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: k3s

    - name: Restart K3s service [agent]
      when: "agent_group in group_names"
      become: true
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: k3s-agent