- name: Ensure timesyncd.conf.d directory exists
  ansible.builtin.file:
    path: '{{ systemd_dir }}/timesyncd.conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: true

- name: "Enable timesyncd service"
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    enabled: true

- name: Set NTP server
  ansible.builtin.template:
    src: 'etc/systemd/timesyncd.conf.d/ansible.conf.j2'
    dest: '{{ systemd_dir }}/timesyncd.conf.d/ansible.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true
  notify:
    - reload systemd
    - restart ntp